-- KerberosScriptCoreLib uses a standalone .csproj (SDK-style, targeting .NET 8.0).
-- Build with: dotnet build KerberosScriptCoreLib/KerberosScriptCoreLib.csproj
-- The externalproject directive includes it in the Visual Studio solution generated by premake.
externalproject "KerberosScriptCoreLib"
	location "."
	kind "SharedLib"
	language "C#"
